<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Bookstore.Data</AssemblyName>
    <Deterministic>true</Deterministic>
    <Nullable>enable</Nullable>
    <RootNamespace>Bookstore.Data</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bookstore.Domain\Bookstore.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="EntityFramework6.Npgsql" Version="6.4.3" />
    <PackageReference Include="Npgsql" Version="5.0.18" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" Version="14.6.0" />
    <PackageReference Include="AWSSDK.Rekognition" Version="3.7.500" />
    <PackageReference Include="AWSSDK.S3" Version="3.7.416.5" />
    <PackageReference Include="EntityFramework" Version="6.5.1" />
    <PackageReference Include="AWSSDK.Core" Version="3.7.500" />
  </ItemGroup>
</Project>