<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <AssemblyName>Bookstore.Web</AssemblyName>
    <RootNamespace>Bookstore.Web</RootNamespace>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Bookstore.Common/Bookstore.Common.csproj" />
    <ProjectReference Include="../Bookstore.Domain/Bookstore.Domain.csproj" />
    <ProjectReference Include="../Bookstore.Data/Bookstore.Data.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Scripts\jquery-3.7.1.intellisense.js" />
    <None Include="Scripts\jquery.validate-vsdoc.js" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AWS.Logger.NLog" Version="5.0.1" />
    <PackageReference Include="Autofac" Version="8.2.1" />
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="8.*" />
    <PackageReference Include="Amazon.Extensions.Configuration.SystemsManager" Version="*" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.3.15" />
    <PackageReference Include="NLog.Extensions.Logging" Version="*" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.100.1" />
    <PackageReference Include="AWSSDK.Rekognition" Version="4.0.100.1" />
    <PackageReference Include="AWSSDK.SimpleSystemsManagement" Version="*" />
    <PackageReference Include="System.ValueTuple" Version="4.6.2" />
  </ItemGroup>
</Project>